networks:
  neo4j-internal:

services:
  neo4j:
    container_name: neo4j
    image: neo4j:5.21
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./database/data:/data
      - ./database/logs:/logs
      - ./database/conf:/conf
    env_file:
      - .env
    restart: on-failure
    networks:
      neo4j-internal:

  server:
    build: ./server
    container_name: server
    image: neo4j-server:1.0.0
    ports:
     - ${SERVER_PORT}:${SERVER_PORT}
    restart: always
    depends_on:
      - neo4j
    env_file:
      - .env
    networks:
      neo4j-internal:
    
